[project]
name = "options"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "loguru>=0.7.3",
    "pandas>=2.3.2",
    "pydantic>=2.11.7",
    "streamlit>=1.49.1",
    "uvicorn>=0.35.0",
]
